name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - develop
      - qa

permissions:
  contents: read
  pull-requests: write

jobs:
  #########################
  # Job Development
  #########################
  build_and_deploy_dev:
    environment: development
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps (Dev)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: "npm run build:dev"

  #########################
  # Job QA
  #########################
  build_and_deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    if: github.ref_name == 'qa'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps (QA)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: "npm run build:qa"

  #########################
  # Job Production
  #########################
  build_and_deploy_prod:
    environment: production
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: "npm run build"
