name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
      - qa
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - branch: develop
            env_name: development
            token_secret: AZURE_STATIC_WEB_APPS_API_TOKEN_DEV
            build_script: npm run build:dev
          - branch: qa
            env_name: qa
            token_secret: AZURE_STATIC_WEB_APPS_API_TOKEN_QA
            build_script: npm run build:qa
          - branch: main
            env_name: production
            token_secret: AZURE_STATIC_WEB_APPS_API_TOKEN_PROD
            build_script: npm run build

    environment: ${{ matrix.env_name }}
    
    steps: 
      - name: Checkout repository
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        run: npm install

      - name: Deploy to Azure Static Web Apps (${{ matrix.env_name }})
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets[matrix.token_secret] }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: ${{ matrix.build_script }}
