name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - develop
      - qa

permissions:
  contents: read
  pull-requests: write

jobs:
  #########################
  # Build único (sube código fuente)
  #########################
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: angular-source
          path: . # 👈 subimos el código completo, no el dist

  #########################
  # Deploy Development
  #########################
  deploy_dev:
    needs: build
    environment: development
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: angular-source
          path: .

      - name: Deploy to Azure Static Web Apps (Dev)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          app_build_command: "npm run build:dev"
          output_location: "dist/portal-integral/browser"

  #########################
  # Deploy QA
  #########################
  deploy_qa:
    needs: build
    environment: qa
    runs-on: ubuntu-latest
    if: github.ref_name == 'qa'
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: angular-source
          path: .

      - name: Deploy to Azure Static Web Apps (QA)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          app_build_command: "npm run build:qa"
          output_location: "dist/portal-integral/browser"

  #########################
  # Deploy Production
  #########################
  deploy_prod:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: angular-source
          path: .

      - name: Deploy to Azure Static Web Apps (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          app_build_command: "npm run build"
          output_location: "dist/portal-integral/browser"
