name: Azure Static Web Apps CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - qa

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref }}
    if: github.event.pull_request.base.ref == 'develop' || github.event.pull_request.base.ref == 'qa'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "develop" ]; then
            npm run build:dev
          elif [ "${{ github.event.pull_request.base.ref }}" == "qa" ]; then
            npm run build:qa
          fi

      - name: Copy staticwebapp.config.json
        run: cp staticwebapp.config.json dist/portal-integral/browser/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build-${{ github.event.pull_request.base.ref }}
          path: dist/portal-integral/browser

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets[ github.event.pull_request.base.ref == 'develop' && 'AZURE_STATIC_WEB_APPS_API_TOKEN_DEV' || 'AZURE_STATIC_WEB_APPS_API_TOKEN_QA' ] }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: |
            if [ "${{ github.event.pull_request.base.ref }}" == "develop" ]; then
              npm run build:dev
            elif [ "${{ github.event.pull_request.base.ref }}" == "qa" ]; then
              npm run build:qa
            fi
