name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - develop
      - qa

permissions:
  contents: read
  pull-requests: write

#########################
# Job Development
#########################
jobs:
  build_and_deploy_dev:
    environment: development
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"

      - name: Clean npm cache
        run: |
          npm cache clean --force
          npx clear-npx-cache

      - name: Install dependencies
        run: npm install

      - name: Build Angular app (Dev)
        run: npm run build:dev

      - name: Copy staticwebapp.config.json
        run: cp staticwebapp.config.json dist/portal-integral/browser/

      - name: Remove host remoteEntry.json
        run: rm -f dist/portal-integral/browser/remoteEntry.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build-dev
          path: dist/portal-integral/browser

      - name: Deploy to Azure Static Web Apps (Dev)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: "npm run build:dev"

  #########################
  # Job QA
  #########################
  build_and_deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    if:  github.ref_name == 'qa'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"

      - name: Clean npm cache
        run: |
          npm cache clean --force
          npx clear-npx-cache

      - name: Install dependencies
        run: npm install

      - name: Build Angular app (QA)
        run: npm run build:qa

      - name: Copy staticwebapp.config.json
        run: cp staticwebapp.config.json dist/portal-integral/browser/

      - name: Remove host remoteEntry.json
        run: rm -f dist/portal-integral/browser/remoteEntry.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build-qa
          path: dist/portal-integral/browser

      - name: Deploy to Azure Static Web Apps (QA)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: "npm run build:qa"

  #########################
  # Job Production
  #########################
  build_and_deploy_prod:
    environment: production
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"

      - name: Clean npm cache
        run: |
          npm cache clean --force
          npx clear-npx-cache

      - name: Install dependencies
        run: npm install

      - name: Build Angular app (Prod)
        run: npm run build

      - name: Copy staticwebapp.config.json
        run: cp staticwebapp.config.json dist/portal-integral/browser/

      - name: Remove host remoteEntry.json
        run: rm -f dist/portal-integral/browser/remoteEntry.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build-prod
          path: dist/portal-integral/browser

      - name: Deploy to Azure Static Web Apps (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/portal-integral/browser"
          app_build_command: "npm run build"
